[versions]
kotlin = "2.0.21"
compose = "1.6.10"
compose-compiler = "1.5.15"
android-gradle = "8.7.3"
serialization = "1.7.0"
datetime = "0.6.1"
coroutines = "1.8.0"
junit = "5.10.2"
activity-compose = "1.9.2"
core-ktx = "1.15.0"

[libraries]
kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }

junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "android-gradle" }
android-library = { id = "com.android.library", version.ref = "android-gradle" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }


